user role
KossKokos/Python_Web_Project pull request #7
Opened 2023-12-10 19:17 UTC by MikeIV2007

В  моделі User було створено поле role яке мoже приймати тілтки три значення. За замовченням це “user”

    roles = Column(String(20), nullable=False, default='user')

    __table_args__ = (
        CheckConstraint(
            role.in_(['admin', 'moderator', 'user']),
            name='check_valid_role'
        ),
    )

У src\repository\users.py до функції create user додана перевірка – якщо новий юзер перший (id== 1) то roles = “admin”. Вінших випадках role = user за замовченням.

async def create_user(body: UserModel, db: Session) -> User:
    user = User(**body.dict())

    db.add(user)
    db.commit()
    print(user)
    if user.id == 1:
        user.role = "admin"
        db.commit()
    db.refresh(user)
    return user

Додан endpont:
@router.patch('/change_role/{user_id}', response_model=UserResponce)
user - admin може змінити роль любого юзера, викликавши його по ID.

До моделі User було додане поле role.
!!! Важливо для подальшого користування усім зробити міграцію бази данних

У src\schemas\users.py додана схема:

class UserRoleUpdate(BaseModel):
    role: str = "role"

Та оновлена схема:

class UserResponce(BaseModel):
    id: int = 1
    username: str = 'username'
    email: EmailStr = 'example@gmail.com'
    password: str = 'password'
    #avatar: str = 'avatar_url'
    avatar: Optional[str] = None
    role: str = "role"

    class Config:
        orm_mode = True

(при зверненні до enpoint @router.get('/me', response_model=UserResponce) падав сервер через відсутній аватар. Добаленно None зазамовченням. орігінальна строка закоменчена)

2023-12-10 20:04 UTC, KossKokos requested changes

2023-12-10 20:04 UTC, KossKokos commented on killer_instagram/src/routes/auth.py
Потім, можливо, прийдеться створити admin router і перенести шляхи туди, в адмінів буде багато функціоналу. На разі додати перевірки і все. Гарна робота

2023-12-10 20:04 UTC, KossKokos commented on killer_instagram/src/database/mod_rep.py
цей файл можете видалити

2023-12-11 07:50 UTC, MikeIV2007 commented
Всі зміни виконані. Потрібно протесувати та замерджети пул реквест

2023-12-11 09:56 UTC, MikeIV2007 commented on killer_instagram/src/routes/auth.py
В src\routes\auth.py ввВ src\routes\auth.py введені додаткові вимоги що до ролей:
Юзер не може змінити свою роль:
if current_user.id == user_id:
        raise HTTPException(status_code=403, detail="Permission denied. Own role cannot be changed.")
Роль суперамина (id=1)не може бути змінена:
if user.id == 1:
        raise HTTPException(status_code=403, detail="Permission denied.Superadmin role cannot be changed.")

Роль “admin” може змінювати тільки суперамин (id=1)
if user.role == "admin" and current_user.id != 1:
        raise HTTPException(status_code=403, detail="Permission denied.Admin role can be changed only by Superadmin (id=1).")
едені додаткові вимоги що до ролей:
Юзер не може змінити свою роль:
if current_user.id == user_id:
        raise HTTPException(status_code=403, detail="Permission denied. Own role cannot be changed.")
Роль суперамина (id=1)не може бути змінена:
if user.id == 1:
        raise HTTPException(status_code=403, detail="Permission denied.Superadmin role cannot be changed.")

Роль “admin” може змінювати тільки суперамин (id=1)
if user.role == "admin" and current_user.id != 1:
        raise HTTPException(status_code=403, detail="Permission denied.Admin role can be changed only by Superadmin (id=1).")

2023-12-11 09:57 UTC, MikeIV2007 commented on killer_instagram/src/database/mod_rep.py
Видалив.

2023-12-11 10:43 UTC, KossKokos approved these changes

2023-12-11 10:44 UTC, merged